
development:
    key: 54f7cf6cb7906adfab9cf9b78959d57d
    secret: f1f120d91c12b6bf598bd20b9c7685e8
    canvas_path: /sympacttest/
    callback_path: http://www.sympact.net
    tunnel:
      username: smartocci
      host: td1.sympact.net
      port: 8888
      local_port: 3000

test:
    key: YOUR_API_KEY_HERE
    secret: YOUR_API_SECRET_HERE
    canvas_path: /yourAppName/
    callback_path: /path/to/your/callback/
    tunnel:
      username: yourLoginName
      host: www.yourexternaldomain.com
      port: 1234
      local_port: 5678

staging:
    key: adb7e39670c9b66d72ea7fd12e477f99
    secret: 831581055b087e694a93a2c9cae0df94
    canvas_path: /standforus/
    callback_path: http://standfor.eval.sympact.net

production:
    key: b0a5a113a615767e72f94827a3d4ce6b
    secret: 5bdcaadab6930821165c1b32054937ce
    canvas_path: /standfor/
    callback_path: http://www.standfor.us