development:
    user: quentin
    pass: test
    younety_app: 1
    url: http://0.0.0.0:3001

test:
    user: quentin
    pass: test
    younety_app: 1
    url: http://adiserver.eval.sympact.net

staging:
    user: quentin
    pass: test
    younety_app: 1
    url: http://adiserver.eval.sympact.net

production:
    user: quentin
    pass: test
    younety_app: 1
    url: http://adiserver.sympact.net
