# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "accounts", :force => true do |t|
    t.column "first_name", :string
    t.column "last_name",  :string
    t.column "phone",      :string
    t.column "email",      :string
    t.column "city",       :string
    t.column "state",      :string
    t.column "zip",        :string
    t.column "created_at", :date
    t.column "updated_at", :date
    t.column "status",     :boolean, :default => true
  end

end
